services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root # The username for the PostgreSQL database
      POSTGRES_PASSWORD: root # The password for the PostgreSQL database
      POSTGRES_DB: test_db # The name of the default database to be created
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgsql_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pdadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - pgsql_network

networks:
  pgsql_network:

volumes:
  pgdata:
